questions:
  - What RANS model works best for a simple boundary layer?
datasets:
  - path: data/jhtdb-profiles.h5
    title: Time-averaged data
    description: Time-averaged data downloaded from the JHTDB website.
    stage:
    imported_from:
      project: petebachant/boundary-layer-turbulence-modeling
      path: data/jhtdb-transitional-bl/time-ave-profiles.h5
      git_rev:
environments:
  foam:
    kind: docker
    image: openfoam-2406-foampy
    wdir: /work
    path: Dockerfile
    user: root
    description: OpenFOAM v2406 with foamPy.
    layers:
      - mambaforge
      - foampy
  latex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive full.
pipeline:
  stages:
    run-sim:
      kind: python-script
      script_path: run.py
      environment: foam
      args:
        - --overwrite
        - --turbulence-model
        - "{turbulence_model}"
      inputs:
        - system
        - constant/transportProperties
      iterate_over:
        - arg_name: turbulence_model
          values:
            - laminar
            - k-epsilon
            - k-omega
      outputs:
        - cases/{turbulence_model}/postProcessing
    plot-mean-velocity-profiles:
      kind: python-script
      script_path: scripts/plot-mean-velocity-profiles.py
      environment: foam
      inputs:
        - from_stage_outputs: run-sim
        - data/jhtdb-profiles.h5
      outputs:
        - figures/mean-velocity-profiles.png
    build-paper:
      kind: latex
      target_path: paper/paper.tex
      environment: latex
      inputs:
        - from_stage_outputs: plot-mean-velocity-profiles
      outputs:
        - paper/paper.pdf
figures:
  - path: figures/mean-velocity-profiles.png
    title: Mean velocity profiles
    description: Mean velocity profiles from DNS and RANS models.
    stage: plot-mean-velocity-profiles
publications:
  - path: ./paper/paper.pdf
    kind: journal-article
    title: Validating RANS models
    description: This was created for a demo.
    stage: build-paper
showcase:
  - figure: figures/mean-velocity-profiles.png
