stages:
  run-sim:
    foreach:
      - laminar
      - k-epsilon
      - k-omega
    do:
      cmd: calkit xenv -n foam -- python run.py --turbulence-model ${item} -f
      outs:
        - cases/${item}/postProcessing
      deps:
        - system
        - constant/transportProperties
        - run.py
        - Dockerfile
  plot-mean-velocity-profiles:
    cmd: calkit xenv -n foam -- python scripts/plot-mean-velocity-profiles.py
    deps:
      - cases/k-epsilon/postProcessing
      - cases/k-omega/postProcessing
      - cases/laminar/postProcessing
      - data/jhtdb-profiles.h5
      - scripts/plot-mean-velocity-profiles.py
      - Dockerfile
    outs:
      - figures/mean-velocity-profiles.png
  build-paper:
    cmd: >
      calkit xenv -n latex --
      latexmk -interaction=nonstopmode -cd -pdf paper/paper.tex
    deps:
      - .calkit/environments/latex.yaml
      - paper/paper.tex
      - figures/mean-velocity-profiles.png
    outs:
      - paper/paper.pdf
