stages:
  build-docker:
    cmd: calkit build-docker openfoam-2406-foampy -i Dockerfile
    deps:
      - Dockerfile
    outs:
      - Dockerfile-lock.json:
          cache: false
          persist: true
    always_changed: true
  run-sim:
    foreach:
      - laminar
      - k-epsilon
      - k-omega
    do:
      cmd: calkit runenv python run.py --turbulence-model ${item} -f
      outs:
        - cases/${item}/postProcessing
      deps:
        - system
        - constant/transportProperties
        - run.py
        - Dockerfile-lock.json
