stages:
  _check-env-foam:
    cmd: calkit check docker-env openfoam-2406-foampy -i Dockerfile -o .calkit/env-locks/foam.json
    deps:
      - Dockerfile
    outs:
      - .calkit/env-locks/foam.json:
          cache: false
          persist: true
    always_changed: true
  _check-env-latex:
    cmd: calkit check docker-env texlive/texlive:latest-full -o .calkit/env-locks/latex.json
    deps: []
    outs:
      - .calkit/env-locks/latex.json:
          cache: false
          persist: true
    always_changed: true
  run-sim:
    cmd: calkit xenv -n foam --no-check -- python run.py --overwrite --turbulence-model
      ${item.turbulence_model}
    deps:
      - run.py
      - system
      - constant/transportProperties
      - .calkit/env-locks/foam.json
    outs:
      - cases/${item.turbulence_model}/postProcessing
    matrix:
      turbulence_model:
        - laminar
        - k-epsilon
        - k-omega
  plot-mean-velocity-profiles:
    cmd: calkit xenv -n foam --no-check -- python scripts/plot-mean-velocity-profiles.py
    deps:
      - scripts/plot-mean-velocity-profiles.py
      - data/jhtdb-profiles.h5
      - .calkit/env-locks/foam.json
      - cases/laminar/postProcessing
      - cases/k-omega/postProcessing
      - cases/k-epsilon/postProcessing
    outs:
      - figures/mean-velocity-profiles.png
  build-paper:
    cmd: calkit xenv -n latex --no-check -- latexmk -cd -interaction=nonstopmode
      -pdf paper/paper.tex
    deps:
      - paper/paper.tex
      - .calkit/env-locks/latex.json
      - figures/mean-velocity-profiles.png
    outs:
      - paper/paper.pdf
